services:

  fastapi:
    build: .
    container_name: enterprise_rag_api

    command:
      uvicorn app.api:app
      --host 0.0.0.0
      --port 8000

    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5:7b

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data


  streamlit:
    build: .
    container_name: enterprise_rag_ui

    command:
      streamlit run ui/streamlit_app.py
      --server.address=0.0.0.0
      --server.port=8501

    environment:
      - FASTAPI_URL=http://fastapi:8000

    ports:
      - "8501:8501"

    depends_on:
      - fastapi